baseURL: "https://nstromberg.github.io/travel-blog/"
languageCode: "en-us"
defaultContentLanguageInSubdir: false
title: "Nathan and Syd Do NYC"
theme: "PaperMod"

params:
  homeInfoParams:
    Title: "NBS in NYC"
    Content: "Exploring Post-Robert Moses Landscapes"

  socialIcons:
    - name: "github"
      url: "https://github.com/nstromberg"

menu:
  main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1
    - identifier: "gallery"
      name: "Gallery"
      url: "/gallery/"
      weight: 3
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 2

